-- MySQL Script generated by MySQL Workbench
-- Tue Feb 16 10:48:18 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cidade_carnes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cidade_carnes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cidade_carnes` DEFAULT CHARACTER SET utf8 ;
USE `cidade_carnes` ;

-- -----------------------------------------------------
-- Table `cidade_carnes`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cidade_carnes`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `classificacao` VARCHAR(45) NOT NULL,
  `origem` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`),
  UNIQUE INDEX `idCategoria_UNIQUE` (`idCategoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cidade_carnes`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cidade_carnes`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DOUBLE NOT NULL,
  `corte` VARCHAR(45) NOT NULL,
  `indicacao` VARCHAR(45) NOT NULL,
  `fk_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idProduto`, `fk_idCategoria`),
  UNIQUE INDEX `idProduto_UNIQUE` (`idProduto` ASC) VISIBLE,
  INDEX `fk_Produto_Categoria_idx` (`fk_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_Categoria`
    FOREIGN KEY (`fk_idCategoria`)
    REFERENCES `cidade_carnes`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
